### ISSUE TITLE
'dataset_total_df' is not defined

### ISSUE THREAD

**Issue by marvin-hansen** [borisbanushev/stockpredictionai#10]
Hi Boris,

thanks for sharing your repo. I am trying hard to replicate your work in a separate notebook and I am struggling with the shape of the total dataset. The document states roughly what's in it and I am trying to reverse engineer, but I stumble over assumed data structures all the time so it wouls be super helpful to post the output of: 

dataset_total_df.shape()

Thank you and keep the good work!

**Comment by suphero** [comment]
Hi @marvin-hansen , I am trying to replicate this work on my repo. I have created a notebook file. I think we should find the missing codes / data on our own. If you are interested my repo path: https://github.com/suphero/stock-prediction-ai

**Comment by TekpreXyz** [comment]
> prediction-ai

link is dead

**Comment by tetrex** [comment]
@suphero can u re-upload the project i'm willing help

**Comment by tetrex** [comment]
any updates regarding dataset_total_df ?

**Comment by suphero** [comment]
@TekpreXyz @tetrex link is working now. I can add you as collaborator if you want.

https://github.com/suphero/stock-prediction-ai
