### ISSUE TITLE
Code and data request

### ISSUE THREAD

**Issue by Fab92** [borisbanushev/stockpredictionai#266]

**Comment by noconstruct** [comment]
Stop opening and closing the issue. Boris isn’t going to send you the full code, he would loose his advantage. You need to learn on your own, you won’t regret it. I am currently seeing a 1% profit on good days with my gekko intergration of his gan.I won’t be sharing my code either as there are a lot of ups and downs with my implementation. Also this is more than enough with some research to get it partially working.

**Comment by Fab92** [comment]
Thank you for your reply, I didn’t want to chase him. I definitely won’t regret learning it on my own. Thanks again!
