### ISSUE TITLE
This seems like a bullshit project given the code is left out and people are requesting/exposing their emails in public issues list

### ISSUE THREAD

**Issue by schlunsen** [borisbanushev/stockpredictionai#299]
Come on guys!

**Comment by noconstruct** [comment]
This is a white paper, it wasn't meant to give lazy people a code base. It was meant to inspire people to create. People requesting code and demanding things is why the author of the article does not respond. If any of these people had taken the time to write their own code they would already have their own working Gan. I do, and I won't be sharing my work with lazy ignorant people.
